--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/drirainMCBE/CommandPlus
build-by-default: true
branches:
- master
projects:
  CommandPlus:
    path: ""
    model: virion
    type: library
...
